.\" Copyright (c) 2024 CodexUniversalis (codexuniversalisprime@gmail.com)
.\"
.\" 2025-04-27 CodexUniversalis - Wrote the man page.
.\" 2025-05-19 CodexUniversalis - Add periods to the example struct.
.\"
.TH LOGC4_MSG_T 7 2025-04-27 CodexUniversalis "LogC4 Library Manual"
.SH NAME
logc4_msg_t \- the
.I LogC4
library enum for message type
.SH DESCRIPTION
.TP
.I logc4_msg_t
.PP
.RS
.IR Include : <logc4.h> .
.PP
.EX
struct logc4_msg_t {
    LOGC4_ERROR,   /* Log message is of type ERROR. */
    LOGC4_WARNING, /* Log message is of type WARNING. */
    LOGC4_INFO,    /* Log message is of type INFO. */
    LOGC4_DEBUG    /* Log message is of type DEBUG. */
}
.EE
.PP
This contains all required information for the log message type.
.RE
.SH AUTHOR
Written by CodexUniversalis
.RI ( codexuniversalis@gmail.com ).
.SH COPYRIGHT
Copyright © 2025 CodexUniversalis. License
.IR MIT .
.SH GITHUB
Here is a link to the GitHub repository for the
.I LogC4
library:
\%https://github.com/CodexUniversalis/LogC4/.
.SH COLOPHON
This page is part of release 0.1.0 of the
.I LogC4
library. A description of the project, information about reporting bugs, and \
the latest version of this page, can be found at
\%https://projects.codexuniversalis.dev/C/LogC4/.
